services:
  cigniter-docker:
    container_name: cigniter4-docker
    build: .
    volumes:
      - ./cigniter-app:/var/www/html
    ports:
      - 8080:80
  
  mysql_db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql # Persist MySQL data
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: flowers
    ports:
    - 3306:3306

  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data: # Define the named volume